### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by domenmerhar** [domenmerhar/StockScreener#1]
- [ ] Get Every Ticker,
- [ ] EV/FCF over 5 years,
- [ ] Output More Financial Ratios,
